steps:

- id: 'terraform init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      ls
      cd Proyecto1/terraform/environments/main 
      terraform init





- id: 'terraform plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      ls
      cd Proyecto1/terraform/environments/main 
      terraform plan



      

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      ls
      cd Proyecto1/terraform/environments/main 
      terraform apply -auto-approve
