steps:

- id: 'test'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      

      echo "*********** Installing pip ************"
      apk add py3-pip
      pip3 install -U setuptools
      echo "*********** Installing pytest ************"
      pip3 install -U pytest
      echo "*********** Checking code ************"
      cd Proyecto1/cloud_function
      python3 -m pytest test.py

- id: 'terraform init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      ls
      cd Proyecto1/terraform/environments/main 
      terraform init





- id: 'terraform plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      ls
      cd Proyecto1/terraform/environments/main 
      terraform plan



      

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      ls
      cd Proyecto1/terraform/environments/main 
      terraform apply -auto-approve
