
- name: 'deploy to google build'
  steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - main
    - --region=us-central1
    - --source=.
    - --trigger-http
    - --runtime=python39

