steps:
- id: 'code check'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "************************************"
      echo "Checking Code in branch $BRANCH_NAME"
      echo "************************************"
      echo "*********** Installing pip ************"
      apk add py3-pip
      pip3 install -U setuptools
      echo "*********** Installing pylint ************"
      pip3 install -U pylint
      echo "*********** Checking code ************"
      cd Proyecto1
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "terraform/enviroments/$BRANCH_NAME/" ]; then
        ls
        cd terraform/enviroments/$BRANCH_NAME
        terraform init
      else
        ls
        for dir in terraform/enviroments/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../../../../../
        done
      fi 
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d " terraform/enviroments/$BRANCH_NAME/" ]; then
        cd  terraform/enviroments/$BRANCH_NAME
        terraform plan
      else
        for dir in  terraform/environments/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../../../../../
        done
      fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d " terraform/enviroments/$BRANCH_NAME/" ]; then
        cd  terraform/enviroments/$BRANCH_NAME      
        terraform apply -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
        echo "*******************************************************************************"
      fi
# [END tf-apply]